openapi: 3.1.0
info:
  title: Sample API
  version: 1.0.0
components:
  schemas:
    SampleModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "ID"
        name:
          type: string
          description: "名前"
