openapi: 3.1.0
info:
  title: Sample API
  version: 1.0.0
components:
  schemas:
    PackageSelectModel:
      custom-package: "com.app.model.xxx" #独自のプロパティを作る
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "The unique identifier for a sample model"
        name:
          type: string
          description: "The name of the sample model"
